/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

import carrental.*;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.ComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import net.sourceforge.jdatepicker.JDatePicker;
import org.apache.commons.dbcp.BasicDataSource;

/**
 *
 * @author ansy
 */
public class MainWindow extends javax.swing.JFrame {

    private CarsManager carsManager;
    private DriversManager driversManager;
    private RentalsManager rentalsManager;
    private CarsTableModel carsModel;
    private int showCars = 0;
    private int showDrivers = 0;
    private int showRentals = 0;
    private String filterString = null;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initManagers();
      /*  for(char i='a';i <= 'z';i++){
            Car c = new Car();
            c.setMileage(20.0);
            c.setName(i + "");
            c.setSpz(i + "");
            c.setVin(i + "");
            carsManager.createCar(c);
        }*/
        initComponents();
        jTableCars.getTableHeader().setReorderingAllowed(false);
        carsModel.addTableModelListener(carsModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editors.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenuItem3 = new javax.swing.JMenuItem();
                jPopupMenu1 = new javax.swing.JPopupMenu();
                jMenu1 = new javax.swing.JMenu();
                jPopupMenu2 = new javax.swing.JPopupMenu();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTree1 = new javax.swing.JTree();
                jMenuBar2 = new javax.swing.JMenuBar();
                jMenu5 = new javax.swing.JMenu();
                jMenu6 = new javax.swing.JMenu();
                jMenu2 = new javax.swing.JMenu();
                buttonGroup1 = new javax.swing.ButtonGroup();
                jMenu3 = new javax.swing.JMenu();
                jScrollPane8 = new javax.swing.JScrollPane();
                jTable5 = new javax.swing.JTable();
                CreateRentalDialog = new javax.swing.JDialog();
                jButtonCRDOk = new javax.swing.JButton();
                jButtonCRDCancel = new javax.swing.JButton();
                jComboBoxCRDCar = new javax.swing.JComboBox();
                jComboBoxCRDDriver = new javax.swing.JComboBox();
                jLabelCRDCar = new javax.swing.JLabel();
                jLabelCRDDriver = new javax.swing.JLabel();
                jLabelCRDPrice = new javax.swing.JLabel();
                jTextFieldCRDPrice = new javax.swing.JTextField();
                jLabelCRDStartTime = new javax.swing.JLabel();
                jTextFieldCRDStartTime = new javax.swing.JTextField();
                jLabelCRDExEndTime = new javax.swing.JLabel();
                jTextFieldCRDExEndTime = new javax.swing.JTextField();
                CreateDriverDialog = new javax.swing.JDialog();
                jButtonCDDOk = new javax.swing.JButton();
                jButtonCDDCancel = new javax.swing.JButton();
                jLabelCDDName = new javax.swing.JLabel();
                jTextFieldCDDName = new javax.swing.JTextField();
                jLabelCDDSurname = new javax.swing.JLabel();
                jTextFieldCDDSurname = new javax.swing.JTextField();
                jLabelCDDLicenseId = new javax.swing.JLabel();
                jTextFieldCDDLicenseId = new javax.swing.JTextField();
                CreateCarDialog = new javax.swing.JDialog();
                jButtonCCDOk = new javax.swing.JButton();
                jButtonCCDCancel = new javax.swing.JButton();
                jLabelCCDVin = new javax.swing.JLabel();
                jTextFieldCCDVin = new javax.swing.JTextField();
                jLabelCCDLicensePlate = new javax.swing.JLabel();
                jTextFieldCCDLicensePlate = new javax.swing.JTextField();
                jLabelCCDModel = new javax.swing.JLabel();
                jTextFieldCCDModel = new javax.swing.JTextField();
                jTextFieldCCDMileage = new javax.swing.JTextField();
                jLabelCCDMileage = new javax.swing.JLabel();
                AboutProgram = new javax.swing.JDialog();
                jButton20 = new javax.swing.JButton();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                Options = new javax.swing.JDialog();
                jButtonOptionsOk = new javax.swing.JButton();
                jButtonOptionsCancel = new javax.swing.JButton();
                jComboBoxOptionsLanguage = new javax.swing.JComboBox();
                jLabelOptionsLanguage = new javax.swing.JLabel();
                DeleteWindow = new javax.swing.JDialog();
                jButton22 = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                jButton23 = new javax.swing.JButton();
                InformationDialog = new javax.swing.JDialog();
                jButtonIDClose = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTextAreaIDinformation = new javax.swing.JTextArea();
                jTabbedPane2 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane6 = new javax.swing.JScrollPane();
                jTableCars = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                carSearchTextField = new javax.swing.JTextField();
                carSearchOkButton = new javax.swing.JButton();
                allCarsRadioButton = new javax.swing.JRadioButton();
                rentedCarsRadioButton = new javax.swing.JRadioButton();
                freeCarsRadioButton = new javax.swing.JRadioButton();
                addCarButton = new javax.swing.JButton();
                deleteCarButton = new javax.swing.JButton();
                carHistoryButton = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jScrollPane7 = new javax.swing.JScrollPane();
                jTable4 = new javax.swing.JTable();
                jPanel4 = new javax.swing.JPanel();
                driverSearchTextField = new javax.swing.JTextField();
                driverSearchOkButton = new javax.swing.JButton();
                addDriverButton = new javax.swing.JButton();
                deleteDriverButton = new javax.swing.JButton();
                driverHistoryButton = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                jPanel6 = new javax.swing.JPanel();
                rentalSearchTextField = new javax.swing.JTextField();
                rentalSearchOkButton = new javax.swing.JButton();
                allRentalsRadioButton = new javax.swing.JRadioButton();
                activeRentalsRadioButton = new javax.swing.JRadioButton();
                finishedRentalsRadioButton = new javax.swing.JRadioButton();
                createRentalButton = new javax.swing.JButton();
                deleteRentalButton = new javax.swing.JButton();
                endRentalButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jTextField5 = new javax.swing.JTextField();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu4 = new javax.swing.JMenu();
                jMenuItemOptions = new javax.swing.JMenuItem();
                jMenuItemAbout = new javax.swing.JMenuItem();
                jMenuItemExit = new javax.swing.JMenuItem();

                jMenuItem3.setText("jMenuItem3");

                jMenu1.setText("jMenu1");

                jScrollPane2.setViewportView(jTree1);

                jMenu5.setText("File");
                jMenuBar2.add(jMenu5);

                jMenu6.setText("Edit");
                jMenuBar2.add(jMenu6);

                jMenu2.setText("jMenu2");

                jMenu3.setText("jMenu3");

                jTable5.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jTable5.setCellSelectionEnabled(true);
                jTable5.setMinimumSize(new java.awt.Dimension(400, 400));
                jScrollPane8.setViewportView(jTable5);

                CreateRentalDialog.setTitle("Create Rental");
                CreateRentalDialog.setMinimumSize(new java.awt.Dimension(300, 220));
                CreateRentalDialog.setPreferredSize(new java.awt.Dimension(300, 220));
                CreateRentalDialog.setResizable(false);

                jButtonCRDOk.setText("OK");
                jButtonCRDOk.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCRDOkActionPerformed(evt);
                        }
                });

                jButtonCRDCancel.setText("Cancel");
                jButtonCRDCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCRDCancelActionPerformed(evt);
                        }
                });

                jComboBoxCRDCar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jComboBoxCRDDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jComboBoxCRDDriver.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBoxCRDDriverActionPerformed(evt);
                        }
                });

                jLabelCRDCar.setText("Car");

                jLabelCRDDriver.setText("Driver");

                jLabelCRDPrice.setText("Price");

                jTextFieldCRDPrice.setText("0");
                jTextFieldCRDPrice.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCRDPriceActionPerformed(evt);
                        }
                });

                jLabelCRDStartTime.setText("Start Time");

                jTextFieldCRDStartTime.setText("0");
                jTextFieldCRDStartTime.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCRDStartTimeActionPerformed(evt);
                        }
                });

                jLabelCRDExEndTime.setText("Expected End time");

                jTextFieldCRDExEndTime.setText("0");
                jTextFieldCRDExEndTime.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCRDExEndTimeActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout CreateRentalDialogLayout = new javax.swing.GroupLayout(CreateRentalDialog.getContentPane());
                CreateRentalDialog.getContentPane().setLayout(CreateRentalDialogLayout);
                CreateRentalDialogLayout.setHorizontalGroup(
                        CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRentalDialogLayout.createSequentialGroup()
                                .addComponent(jButtonCRDCancel)
                                .addGap(0, 0, 0)
                                .addComponent(jButtonCRDOk, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreateRentalDialogLayout.createSequentialGroup()
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CreateRentalDialogLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabelCRDCar))
                                        .addGroup(CreateRentalDialogLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabelCRDPrice))
                                        .addGroup(CreateRentalDialogLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabelCRDDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CreateRentalDialogLayout.createSequentialGroup()
                                                .addComponent(jTextFieldCRDPrice)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRentalDialogLayout.createSequentialGroup()
                                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBoxCRDDriver, 0, 150, Short.MAX_VALUE)
                                                        .addComponent(jComboBoxCRDCar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(10, 10, 10))))
                        .addGroup(CreateRentalDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCRDExEndTime)
                                        .addComponent(jLabelCRDStartTime))
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCRDStartTime)
                                        .addComponent(jTextFieldCRDExEndTime))
                                .addContainerGap())
                );
                CreateRentalDialogLayout.setVerticalGroup(
                        CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateRentalDialogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxCRDCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCRDCar))
                                .addGap(10, 10, 10)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxCRDDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCRDDriver))
                                .addGap(5, 5, 5)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCRDPrice)
                                        .addComponent(jTextFieldCRDPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCRDStartTime)
                                        .addComponent(jTextFieldCRDStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCRDExEndTime)
                                        .addComponent(jTextFieldCRDExEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(CreateRentalDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCRDOk)
                                        .addComponent(jButtonCRDCancel))
                                .addGap(0, 0, 0))
                );

                CreateDriverDialog.setTitle("Create Driver");
                CreateDriverDialog.setMinimumSize(new java.awt.Dimension(300, 160));
                CreateDriverDialog.setPreferredSize(new java.awt.Dimension(300, 160));
                CreateDriverDialog.setResizable(false);

                jButtonCDDOk.setText("OK");
                jButtonCDDOk.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCDDOkActionPerformed(evt);
                        }
                });

                jButtonCDDCancel.setText("Cancel");
                jButtonCDDCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCDDCancelActionPerformed(evt);
                        }
                });

                jLabelCDDName.setText("Name");

                jTextFieldCDDName.setToolTipText("Name");
                jTextFieldCDDName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCDDNameActionPerformed(evt);
                        }
                });

                jLabelCDDSurname.setText("Surname");

                jTextFieldCDDSurname.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCDDSurnameActionPerformed(evt);
                        }
                });

                jLabelCDDLicenseId.setText("Licence ID");

                jTextFieldCDDLicenseId.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCDDLicenseIdActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout CreateDriverDialogLayout = new javax.swing.GroupLayout(CreateDriverDialog.getContentPane());
                CreateDriverDialog.getContentPane().setLayout(CreateDriverDialogLayout);
                CreateDriverDialogLayout.setHorizontalGroup(
                        CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateDriverDialogLayout.createSequentialGroup()
                                .addGap(0, 180, Short.MAX_VALUE)
                                .addComponent(jButtonCDDCancel)
                                .addGap(0, 0, 0)
                                .addComponent(jButtonCDDOk, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreateDriverDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCDDLicenseId)
                                        .addComponent(jLabelCDDSurname)
                                        .addComponent(jLabelCDDName))
                                .addGroup(CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCDDName)
                                        .addComponent(jTextFieldCDDSurname)
                                        .addComponent(jTextFieldCDDLicenseId))
                                .addContainerGap())
                );
                CreateDriverDialogLayout.setVerticalGroup(
                        CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateDriverDialogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCDDName)
                                        .addComponent(jTextFieldCDDName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCDDSurname)
                                        .addComponent(jTextFieldCDDSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCDDLicenseId)
                                        .addComponent(jTextFieldCDDLicenseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(CreateDriverDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCDDOk)
                                        .addComponent(jButtonCDDCancel))
                                .addGap(0, 0, 0))
                );

                CreateCarDialog.setTitle("Create Car");
                CreateCarDialog.setMinimumSize(new java.awt.Dimension(300, 190));
                CreateCarDialog.setResizable(false);

                jButtonCCDOk.setText("OK");
                jButtonCCDOk.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCCDOkActionPerformed(evt);
                        }
                });

                jButtonCCDCancel.setText("Cancel");
                jButtonCCDCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCCDCancelActionPerformed(evt);
                        }
                });

                jLabelCCDVin.setText("VIN");

                jTextFieldCCDVin.setToolTipText("Name");
                jTextFieldCCDVin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCCDVinActionPerformed(evt);
                        }
                });

                jLabelCCDLicensePlate.setText("License plate");
                jLabelCCDLicensePlate.setMaximumSize(new java.awt.Dimension(100, 18));
                jLabelCCDLicensePlate.setMinimumSize(new java.awt.Dimension(100, 18));
                jLabelCCDLicensePlate.setPreferredSize(new java.awt.Dimension(100, 18));

                jTextFieldCCDLicensePlate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCCDLicensePlateActionPerformed(evt);
                        }
                });

                jLabelCCDModel.setText("Model");

                jTextFieldCCDModel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCCDModelActionPerformed(evt);
                        }
                });

                jTextFieldCCDMileage.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldCCDMileageActionPerformed(evt);
                        }
                });

                jLabelCCDMileage.setText("Mileage");

                javax.swing.GroupLayout CreateCarDialogLayout = new javax.swing.GroupLayout(CreateCarDialog.getContentPane());
                CreateCarDialog.getContentPane().setLayout(CreateCarDialogLayout);
                CreateCarDialogLayout.setHorizontalGroup(
                        CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCarDialogLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCCDCancel)
                                .addGap(0, 0, 0)
                                .addComponent(jButtonCCDOk, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CreateCarDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCCDModel)
                                        .addComponent(jLabelCCDLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCCDVin)
                                        .addComponent(jLabelCCDMileage))
                                .addGap(12, 12, 12)
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCCDMileage, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCCDLicensePlate, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldCCDModel)
                                        .addComponent(jTextFieldCCDVin))
                                .addContainerGap())
                );
                CreateCarDialogLayout.setVerticalGroup(
                        CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateCarDialogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCCDVin)
                                        .addComponent(jTextFieldCCDVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCCDLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCCDLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCCDModel)
                                        .addComponent(jTextFieldCCDModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCCDMileage)
                                        .addComponent(jTextFieldCCDMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(CreateCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCCDOk)
                                        .addComponent(jButtonCCDCancel))
                                .addGap(0, 0, 0))
                );

                AboutProgram.setTitle("About");
                AboutProgram.setAlwaysOnTop(true);
                AboutProgram.setMinimumSize(new java.awt.Dimension(250, 180));
                AboutProgram.setModal(true);
                AboutProgram.setResizable(false);

                jButton20.setText("Close");
                jButton20.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton20ActionPerformed(evt);
                        }
                });

                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
                jTextArea1.setRows(5);
                jTextArea1.setText("About\nVersion 12");
                jTextArea1.setFocusable(false);
                jScrollPane3.setViewportView(jTextArea1);

                javax.swing.GroupLayout AboutProgramLayout = new javax.swing.GroupLayout(AboutProgram.getContentPane());
                AboutProgram.getContentPane().setLayout(AboutProgramLayout);
                AboutProgramLayout.setHorizontalGroup(
                        AboutProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutProgramLayout.createSequentialGroup()
                                .addGroup(AboutProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AboutProgramLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutProgramLayout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton20)))
                                .addContainerGap())
                );
                AboutProgramLayout.setVerticalGroup(
                        AboutProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutProgramLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton20)
                                .addGap(5, 5, 5))
                );

                Options.setTitle("Options");
                Options.setMinimumSize(new java.awt.Dimension(250, 110));
                Options.setModal(true);
                Options.setResizable(false);

                jButtonOptionsOk.setText("OK");
                jButtonOptionsOk.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonOptionsOkActionPerformed(evt);
                        }
                });

                jButtonOptionsCancel.setText("Cancel");
                jButtonOptionsCancel.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonOptionsCancelActionPerformed(evt);
                        }
                });

                jComboBoxOptionsLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabelOptionsLanguage.setText("Language");

                javax.swing.GroupLayout OptionsLayout = new javax.swing.GroupLayout(Options.getContentPane());
                Options.getContentPane().setLayout(OptionsLayout);
                OptionsLayout.setHorizontalGroup(
                        OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonOptionsCancel)
                                .addGap(0, 0, 0)
                                .addComponent(jButtonOptionsOk, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(OptionsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelOptionsLanguage)
                                .addGap(13, 13, 13)
                                .addComponent(jComboBoxOptionsLanguage, 0, 162, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                );
                OptionsLayout.setVerticalGroup(
                        OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionsLayout.createSequentialGroup()
                                .addContainerGap(53, Short.MAX_VALUE)
                                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxOptionsLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelOptionsLanguage))
                                .addGap(10, 10, 10)
                                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonOptionsOk)
                                        .addComponent(jButtonOptionsCancel)))
                );

                DeleteWindow.setAlwaysOnTop(true);
                DeleteWindow.setLocationByPlatform(true);
                DeleteWindow.setMinimumSize(new java.awt.Dimension(233, 120));
                DeleteWindow.setModal(true);
                DeleteWindow.setResizable(false);

                jButton22.setText("Yes");
                jButton22.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton22ActionPerformed(evt);
                        }
                });

                jLabel7.setText("Do u really wish to delete?");

                jButton23.setText("No");
                jButton23.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton23ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout DeleteWindowLayout = new javax.swing.GroupLayout(DeleteWindow.getContentPane());
                DeleteWindow.getContentPane().setLayout(DeleteWindowLayout);
                DeleteWindowLayout.setHorizontalGroup(
                        DeleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteWindowLayout.createSequentialGroup()
                                .addContainerGap(65, Short.MAX_VALUE)
                                .addComponent(jButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton22)
                                .addGap(56, 56, 56))
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                DeleteWindowLayout.setVerticalGroup(
                        DeleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteWindowLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(DeleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton22)
                                        .addComponent(jButton23)))
                );

                InformationDialog.setTitle("Information dialog");
                InformationDialog.setMinimumSize(new java.awt.Dimension(386, 250));

                jButtonIDClose.setText("Close");
                jButtonIDClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonIDCloseActionPerformed(evt);
                        }
                });

                jTextAreaIDinformation.setEditable(false);
                jTextAreaIDinformation.setColumns(20);
                jTextAreaIDinformation.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
                jTextAreaIDinformation.setRows(5);
                jScrollPane4.setViewportView(jTextAreaIDinformation);

                javax.swing.GroupLayout InformationDialogLayout = new javax.swing.GroupLayout(InformationDialog.getContentPane());
                InformationDialog.getContentPane().setLayout(InformationDialogLayout);
                InformationDialogLayout.setHorizontalGroup(
                        InformationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InformationDialogLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InformationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationDialogLayout.createSequentialGroup()
                                                .addGap(0, 0, 0)
                                                .addComponent(jButtonIDClose)))
                                .addContainerGap())
                );
                InformationDialogLayout.setVerticalGroup(
                        InformationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationDialogLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButtonIDClose)
                                .addGap(5, 5, 5))
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setLocationByPlatform(true);

                jTabbedPane2.setComponentPopupMenu(jPopupMenu1);
                jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jTabbedPane2.setRequestFocusEnabled(false);

                jPanel1.setName(""); // NOI18N

                jTableCars.setModel(carsModel);
                jTableCars.setEditingColumn(0);
                jTableCars.setEditingRow(0);
                jTableCars.setMinimumSize(new java.awt.Dimension(300, 150));
                jTableCars.setName(""); // NOI18N
                jTableCars.setRequestFocusEnabled(false);
                jTableCars.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                jScrollPane6.setViewportView(jTableCars);
                jTableCars.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

                carSearchTextField.setText("Search");

                carSearchOkButton.setText("ok");
                carSearchOkButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                carSearchOkButtonActionPerformed(evt);
                        }
                });

                buttonGroup1.add(allCarsRadioButton);
                allCarsRadioButton.setText("All");
                allCarsRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                allCarsRadioButtonActionPerformed(evt);
                        }
                });

                buttonGroup1.add(rentedCarsRadioButton);
                rentedCarsRadioButton.setText("Rented");
                rentedCarsRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rentedCarsRadioButtonActionPerformed(evt);
                        }
                });

                buttonGroup1.add(freeCarsRadioButton);
                freeCarsRadioButton.setText("Free");
                freeCarsRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                freeCarsRadioButtonActionPerformed(evt);
                        }
                });

                addCarButton.setText("Add Car");
                addCarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addCarButtonActionPerformed(evt);
                        }
                });

                deleteCarButton.setText("Delete Car");
                deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteCarButtonActionPerformed(evt);
                        }
                });

                carHistoryButton.setText("Car History");
                carHistoryButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                carHistoryButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deleteCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(carSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(carSearchOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(allCarsRadioButton)
                                                        .addComponent(rentedCarsRadioButton)
                                                        .addComponent(freeCarsRadioButton))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(addCarButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(carHistoryButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(carSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(carSearchOkButton))
                                .addGap(15, 15, 15)
                                .addComponent(allCarsRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(rentedCarsRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(freeCarsRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(addCarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carHistoryButton)
                                .addGap(0, 285, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane2.addTab("Cars", jPanel1);

                jPanel2.setName(""); // NOI18N

                jTable4.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "ID", "Name", "Surname", "License ID"
                        }
                ));
                jTable4.setCellSelectionEnabled(true);
                jTable4.setMinimumSize(new java.awt.Dimension(400, 400));
                jScrollPane7.setViewportView(jTable4);
                jTable4.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

                driverSearchTextField.setText("Search");

                driverSearchOkButton.setText("ok");
                driverSearchOkButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                driverSearchOkButtonActionPerformed(evt);
                        }
                });

                addDriverButton.setText("Add Driver");
                addDriverButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addDriverButtonActionPerformed(evt);
                        }
                });

                deleteDriverButton.setText("Delete Driver");
                deleteDriverButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteDriverButtonActionPerformed(evt);
                        }
                });

                driverHistoryButton.setText("Driver History");
                driverHistoryButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                driverHistoryButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(driverSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(driverSearchOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(addDriverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteDriverButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(driverHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(driverSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(driverSearchOkButton))
                                .addGap(15, 15, 15)
                                .addComponent(addDriverButton)
                                .addGap(0, 0, 0)
                                .addComponent(deleteDriverButton)
                                .addGap(0, 0, 0)
                                .addComponent(driverHistoryButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane2.addTab("Drivers", jPanel2);

                jPanel5.setName(""); // NOI18N

                rentalSearchTextField.setText("Search");

                rentalSearchOkButton.setText("ok");
                rentalSearchOkButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rentalSearchOkButtonActionPerformed(evt);
                        }
                });

                buttonGroup1.add(allRentalsRadioButton);
                allRentalsRadioButton.setText("All");
                allRentalsRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                allRentalsRadioButtonActionPerformed(evt);
                        }
                });

                buttonGroup1.add(activeRentalsRadioButton);
                activeRentalsRadioButton.setText("Active");
                activeRentalsRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                activeRentalsRadioButtonActionPerformed(evt);
                        }
                });

                buttonGroup1.add(finishedRentalsRadioButton);
                finishedRentalsRadioButton.setText("Finished");
                finishedRentalsRadioButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                finishedRentalsRadioButtonActionPerformed(evt);
                        }
                });

                createRentalButton.setText("Create Rental");
                createRentalButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                createRentalButtonActionPerformed(evt);
                        }
                });

                deleteRentalButton.setText("Delete Rental");
                deleteRentalButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteRentalButtonActionPerformed(evt);
                        }
                });

                endRentalButton.setText("End Rental");
                endRentalButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                endRentalButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addComponent(rentalSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(rentalSearchOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(allRentalsRadioButton)
                                                        .addComponent(activeRentalsRadioButton)
                                                        .addComponent(finishedRentalsRadioButton))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(createRentalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteRentalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(endRentalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rentalSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rentalSearchOkButton))
                                .addGap(15, 15, 15)
                                .addComponent(allRentalsRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(activeRentalsRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(finishedRentalsRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(createRentalButton)
                                .addGap(0, 0, 0)
                                .addComponent(deleteRentalButton)
                                .addGap(0, 0, 0)
                                .addComponent(endRentalButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null}
                        },
                        new String [] {
                                "ID", "Driver", "Car", "Price", "Start time", "Expected end time", "End time"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                );

                jTabbedPane2.addTab("Rentals", jPanel5);

                jTextField5.setEditable(false);
                jTextField5.setText("Status Bar");
                jTextField5.setEnabled(false);
                jTextField5.setFocusable(false);
                jTextField5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField5ActionPerformed(evt);
                        }
                });

                jMenu4.setText("Menu");
                jMenu4.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                jMenu4KeyPressed(evt);
                        }
                });

                jMenuItemOptions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
                jMenuItemOptions.setText("Options");
                jMenuItemOptions.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemOptionsActionPerformed(evt);
                        }
                });
                jMenu4.add(jMenuItemOptions);

                jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
                jMenuItemAbout.setText("About Program");
                jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemAboutActionPerformed(evt);
                        }
                });
                jMenu4.add(jMenuItemAbout);

                jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
                jMenuItemExit.setText("Exit");
                jMenuItemExit.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jMenuItemExitMouseClicked(evt);
                        }
                });
                jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItemExitActionPerformed(evt);
                        }
                });
                jMenu4.add(jMenuItemExit);

                jMenuBar1.add(jMenu4);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane2)
                        .addComponent(jTextField5)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jTabbedPane2)
                                .addGap(0, 0, 0)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jMenu4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu4KeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jMenu4KeyPressed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:        
      //  dispose();
        System.exit(0);  
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemExitMouseClicked
        // TODO add your handling code here:       
    }//GEN-LAST:event_jMenuItemExitMouseClicked

    private void jMenuItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOptionsActionPerformed
        Options.setLocationRelativeTo(this);        
        Options.setVisible(true);
    }//GEN-LAST:event_jMenuItemOptionsActionPerformed

    private void carSearchOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carSearchOkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carSearchOkButtonActionPerformed

    private void allCarsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCarsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allCarsRadioButtonActionPerformed

    private void rentedCarsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentedCarsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentedCarsRadioButtonActionPerformed

    private void freeCarsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeCarsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freeCarsRadioButtonActionPerformed

    private void addCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarButtonActionPerformed
	   this.clearCreateCarDialog();
	   this.CreateCarDialog.setLocationRelativeTo(this);
	   this.CreateCarDialog.setVisible(true);
    }//GEN-LAST:event_addCarButtonActionPerformed

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        DeleteWindow.setLocationRelativeTo(this);
        DeleteWindow.setVisible(true);            
    }//GEN-LAST:event_deleteCarButtonActionPerformed

    private void driverSearchOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverSearchOkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverSearchOkButtonActionPerformed

    private void addDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverButtonActionPerformed
        this.clearCreateDriverDialog();
	this.CreateDriverDialog.setLocationRelativeTo(this);
	this.CreateDriverDialog.setVisible(true);
    }//GEN-LAST:event_addDriverButtonActionPerformed

    private void deleteDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDriverButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDriverButtonActionPerformed

    private void rentalSearchOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalSearchOkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentalSearchOkButtonActionPerformed

    private void allRentalsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRentalsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allRentalsRadioButtonActionPerformed

    private void activeRentalsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeRentalsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeRentalsRadioButtonActionPerformed

    private void finishedRentalsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedRentalsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishedRentalsRadioButtonActionPerformed

    private void createRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRentalButtonActionPerformed
        
	//load cars
	CarComboBoxModel carComboBoxModel = new CarComboBoxModel(this.carsManager);
	this.jComboBoxCRDCar.setModel(carComboBoxModel);
	    
	//load drivers
	DriverComboBoxModel driverComboBoxModel = new DriverComboBoxModel(this.driversManager);
	this.jComboBoxCRDDriver.setModel(driverComboBoxModel);
	    
	    
	this.clearCreateRentalDialog();
	this.CreateRentalDialog.setLocationRelativeTo(this);
	this.CreateRentalDialog.setVisible(true);
    }//GEN-LAST:event_createRentalButtonActionPerformed

    private void deleteRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRentalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRentalButtonActionPerformed

    private void carHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carHistoryButtonActionPerformed

    private void driverHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverHistoryButtonActionPerformed

    private void endRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endRentalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endRentalButtonActionPerformed

    private void jTextFieldCRDPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCRDPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCRDPriceActionPerformed

    private void jTextFieldCRDStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCRDStartTimeActionPerformed
        //
    }//GEN-LAST:event_jTextFieldCRDStartTimeActionPerformed

    private void jTextFieldCRDExEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCRDExEndTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCRDExEndTimeActionPerformed

    private void jTextFieldCDDLicenseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCDDLicenseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCDDLicenseIdActionPerformed

    private void jTextFieldCDDSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCDDSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCDDSurnameActionPerformed

    private void jTextFieldCDDNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCDDNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCDDNameActionPerformed

    private void jTextFieldCCDVinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCDVinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCDVinActionPerformed

    private void jTextFieldCCDLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCDLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCDLicensePlateActionPerformed

    private void jTextFieldCCDModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCDModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCDModelActionPerformed

    private void jTextFieldCCDMileageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCDMileageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCDMileageActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        carsModel.removeRow(jTableCars.getSelectedRow(), jTableCars);
        DeleteWindow.dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        DeleteWindow.dispose();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
     AboutProgram.setLocationRelativeTo(this);
        AboutProgram.setVisible(true);  
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

        private void jButtonCCDCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCDCancelActionPerformed
                this.CreateCarDialog.dispose();
        }//GEN-LAST:event_jButtonCCDCancelActionPerformed

        private void jButtonCCDOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCDOkActionPerformed
		try {
			//control input data
			this.controlInputText(this.jTextFieldCCDVin);
			this.controlInputText(this.jTextFieldCCDLicensePlate);
			this.controlInputText(this.jTextFieldCCDModel);
			this.controlInputText(this.jTextFieldCCDMileage);
			
			//get data
			String vin = this.jTextFieldCCDVin.getText();
			String licensePlate = this.jTextFieldCCDLicensePlate.getText();
			String model = this.jTextFieldCCDModel.getText();
			String mileageStr = this.jTextFieldCCDMileage.getText();
			
			//convert str to double
			Double mileage = Double.valueOf(mileageStr);
			
			//create car
			Car car = new Car(null, vin, licensePlate, model, mileage);
			this.carsManager.createCar(car);
	
			//data was changed, info to datamodel
			this.carsModel.fireTableDataChanged();
			
			//hide dialog
			this.CreateCarDialog.dispose();
			
			
		} catch (Exception ex) {
			Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
			this.displayInformationDialog("Problem with adding new car.\nMaybe any information are bad.");
		}
		
		
        }//GEN-LAST:event_jButtonCCDOkActionPerformed

        private void jButtonIDCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIDCloseActionPerformed
                this.InformationDialog.setVisible(false);
        }//GEN-LAST:event_jButtonIDCloseActionPerformed

        private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
                this.AboutProgram.dispose();
        }//GEN-LAST:event_jButton20ActionPerformed

        private void jButtonOptionsOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsOkActionPerformed
                //ok button - options
		
		this.Options.dispose();
        }//GEN-LAST:event_jButtonOptionsOkActionPerformed

        private void jButtonOptionsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOptionsCancelActionPerformed
               this.Options.dispose();
        }//GEN-LAST:event_jButtonOptionsCancelActionPerformed

        private void jButtonCDDCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCDDCancelActionPerformed
                this.CreateDriverDialog.dispose();
        }//GEN-LAST:event_jButtonCDDCancelActionPerformed

        private void jButtonCDDOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCDDOkActionPerformed
                try {
			//control input data
			this.controlInputText(this.jTextFieldCDDName);
			this.controlInputText(this.jTextFieldCDDSurname);
			this.controlInputText(this.jTextFieldCDDLicenseId);
			
			//get data
			String name = this.jTextFieldCDDName.getText();
			String surname = this.jTextFieldCDDSurname.getText();
			String licenseId = this.jTextFieldCDDLicenseId.getText();
			
			//create driver
			Driver driver = new Driver(null, name, surname, licenseId);
			this.driversManager.createDriver(driver);
	
			//data was changed, info to datamodel
			//this.driversModel.fireTableDataChanged();
			
			//hide dialog
			this.CreateDriverDialog.dispose();
			
			
		} catch (Exception ex) {
			Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
			this.displayInformationDialog("Problem with adding new driver.\nMaybe any information are bad.");
		}
        }//GEN-LAST:event_jButtonCDDOkActionPerformed

        private void jComboBoxCRDDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCRDDriverActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jComboBoxCRDDriverActionPerformed

        private void jButtonCRDCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRDCancelActionPerformed
                this.CreateRentalDialog.dispose();
        }//GEN-LAST:event_jButtonCRDCancelActionPerformed

        private void jButtonCRDOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRDOkActionPerformed
                this.CreateRentalDialog.dispose();
        }//GEN-LAST:event_jButtonCRDOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // make sure this is only instance of this program
        Utils.initProgram();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JDialog AboutProgram;
        private javax.swing.JDialog CreateCarDialog;
        private javax.swing.JDialog CreateDriverDialog;
        private javax.swing.JDialog CreateRentalDialog;
        private javax.swing.JDialog DeleteWindow;
        private javax.swing.JDialog InformationDialog;
        private javax.swing.JDialog Options;
        private javax.swing.JRadioButton activeRentalsRadioButton;
        private javax.swing.JButton addCarButton;
        private javax.swing.JButton addDriverButton;
        private javax.swing.JRadioButton allCarsRadioButton;
        private javax.swing.JRadioButton allRentalsRadioButton;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JButton carHistoryButton;
        private javax.swing.JButton carSearchOkButton;
        private javax.swing.JTextField carSearchTextField;
        private javax.swing.JButton createRentalButton;
        private javax.swing.JButton deleteCarButton;
        private javax.swing.JButton deleteDriverButton;
        private javax.swing.JButton deleteRentalButton;
        private javax.swing.JButton driverHistoryButton;
        private javax.swing.JButton driverSearchOkButton;
        private javax.swing.JTextField driverSearchTextField;
        private javax.swing.JButton endRentalButton;
        private javax.swing.JRadioButton finishedRentalsRadioButton;
        private javax.swing.JRadioButton freeCarsRadioButton;
        private javax.swing.JButton jButton20;
        private javax.swing.JButton jButton22;
        private javax.swing.JButton jButton23;
        private javax.swing.JButton jButtonCCDCancel;
        private javax.swing.JButton jButtonCCDOk;
        private javax.swing.JButton jButtonCDDCancel;
        private javax.swing.JButton jButtonCDDOk;
        private javax.swing.JButton jButtonCRDCancel;
        private javax.swing.JButton jButtonCRDOk;
        private javax.swing.JButton jButtonIDClose;
        private javax.swing.JButton jButtonOptionsCancel;
        private javax.swing.JButton jButtonOptionsOk;
        private javax.swing.JComboBox jComboBoxCRDCar;
        private javax.swing.JComboBox jComboBoxCRDDriver;
        private javax.swing.JComboBox jComboBoxOptionsLanguage;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabelCCDLicensePlate;
        private javax.swing.JLabel jLabelCCDMileage;
        private javax.swing.JLabel jLabelCCDModel;
        private javax.swing.JLabel jLabelCCDVin;
        private javax.swing.JLabel jLabelCDDLicenseId;
        private javax.swing.JLabel jLabelCDDName;
        private javax.swing.JLabel jLabelCDDSurname;
        private javax.swing.JLabel jLabelCRDCar;
        private javax.swing.JLabel jLabelCRDDriver;
        private javax.swing.JLabel jLabelCRDExEndTime;
        private javax.swing.JLabel jLabelCRDPrice;
        private javax.swing.JLabel jLabelCRDStartTime;
        private javax.swing.JLabel jLabelOptionsLanguage;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenu jMenu3;
        private javax.swing.JMenu jMenu4;
        private javax.swing.JMenu jMenu5;
        private javax.swing.JMenu jMenu6;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuBar jMenuBar2;
        private javax.swing.JMenuItem jMenuItem3;
        private javax.swing.JMenuItem jMenuItemAbout;
        private javax.swing.JMenuItem jMenuItemExit;
        private javax.swing.JMenuItem jMenuItemOptions;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPopupMenu jPopupMenu1;
        private javax.swing.JPopupMenu jPopupMenu2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane6;
        private javax.swing.JScrollPane jScrollPane7;
        private javax.swing.JScrollPane jScrollPane8;
        private javax.swing.JTabbedPane jTabbedPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable4;
        private javax.swing.JTable jTable5;
        private javax.swing.JTable jTableCars;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextArea jTextAreaIDinformation;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextFieldCCDLicensePlate;
        private javax.swing.JTextField jTextFieldCCDMileage;
        private javax.swing.JTextField jTextFieldCCDModel;
        private javax.swing.JTextField jTextFieldCCDVin;
        private javax.swing.JTextField jTextFieldCDDLicenseId;
        private javax.swing.JTextField jTextFieldCDDName;
        private javax.swing.JTextField jTextFieldCDDSurname;
        private javax.swing.JTextField jTextFieldCRDExEndTime;
        private javax.swing.JTextField jTextFieldCRDPrice;
        private javax.swing.JTextField jTextFieldCRDStartTime;
        private javax.swing.JTree jTree1;
        private javax.swing.JButton rentalSearchOkButton;
        private javax.swing.JTextField rentalSearchTextField;
        private javax.swing.JRadioButton rentedCarsRadioButton;
        // End of variables declaration//GEN-END:variables

    private void initManagers() throws ServiceFailureException {
        Properties prop = new Properties();
        BasicDataSource dataSource;
        
        try {
            prop.load(new FileInputStream("db.properties"));

            dataSource = new BasicDataSource();
            dataSource.setUrl(prop.getProperty("url"));
            dataSource.setUsername(prop.getProperty("username"));
            dataSource.setPassword(prop.getProperty("password"));

        } catch (IOException ex) {
            throw new ServiceFailureException("Internal error: couldn't load properties", ex);
        }
        carsManager = new CarsManager(dataSource);
	driversManager = new DriversManager(dataSource);
	rentalsManager = new RentalsManager(dataSource);
	
        carsModel = new CarsTableModel(carsManager);
    }
    
     private void controlInputText(JTextField textField) throws IllegalAccessException {
	    if(textField.getText().isEmpty()) {
		    textField.setBackground(Color.YELLOW);
		    throw new IllegalAccessException("TextField is Empty");
	    } else {
		   textField.setBackground(Color.white); 
	    }
    }
     
    private void displayInformationDialog(String text) {
	    this.jTextAreaIDinformation.setText(text);
	    this.InformationDialog.setLocationRelativeTo(this);
	    this.InformationDialog.setVisible(true);
    } 
    
      private void clearCreateCarDialog() {
	this.jTextFieldCCDVin.setText("");
	this.jTextFieldCCDModel.setText("");
	this.jTextFieldCCDLicensePlate.setText("");
	this.jTextFieldCCDMileage.setText("");
    }
    
    private void clearCreateDriverDialog() {
	this.jTextFieldCDDName.setText("");
	this.jTextFieldCDDSurname.setText("");
	this.jTextFieldCDDLicenseId.setText("");
    }
    
    private void clearCreateRentalDialog() {
	this.jTextFieldCRDPrice.setText("");
	this.jTextFieldCRDStartTime.setText("");
	this.jTextFieldCRDExEndTime.setText("");
	this.jComboBoxCRDCar.setSelectedIndex(0);
	this.jComboBoxCRDDriver.setSelectedIndex(0);
    }
}
